//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoWalletDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP
    {
        public int OTPId { get; set; }
        public string OTP1 { get; set; }
        public string ReferenceId { get; set; }
        public System.DateTime ExpiryDateTime { get; set; }
        public byte OTPPurposeId { get; set; }
        public bool IsValid { get; set; }
    
        public virtual OTPPurpose OTPPurpose { get; set; }
    }
}
