//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmigoWalletDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public long UserTransactionId { get; set; }
        public string EmailId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public byte PaymentTypeId { get; set; }
        public string Remarks { get; set; }
        public string Info { get; set; }
        public byte StatusId { get; set; }
        public short PointsEarned { get; set; }
        public bool IsRedeemed { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Status Status { get; set; }
    }
}
